before_install:
 - sudo apt-get update
 - sudo apt-get install -qq desktop-file-utils
 - if [ -z "$PERLBREW_PERL" ]; then eval $(curl https://travis-perl.github.io/init) --perl; fi
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.22-shrplib"
  - "5.24"
  - "5.24-shrplib"
  - "5.26"
  - "5.26-shrplib"
  - "5.28"
  - "5.30"
